version: '2'
services:
  phpfpm:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: ktcshopify:latest
    working_dir: /app
    volumes:
     - php-socket:/var/run
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    working_dir: /app
    image: ktcshopify-nginx:latest
    ports:
     - 80:80
     - 443:443
    volumes:
     - php-socket:/var/run
volumes:
  php-socket:
    driver: local
